server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/focus_app_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
email:
  from: tilemarket2022@gmail.com
  password: auogzmiqdjuyxbji