server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/focus_app_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 668553925343-met3vqnbsb1msmtoo0l2hop9usq12md9.apps.googleusercontent.com
            client-secret: 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
email:
  from: wealthuring@gmail.com
  password: oaunszrvljseonid
  link: http://localhost:8081